dist: xenial
language: rust
services: docker
sudo: required

matrix:
  include:
    # Rust stable
    - rust: stable
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - RUSTFLAGS="-C link-dead-code"
    - os: osx
      rust: stable
      env:
      - TARGET=x86_64-apple-darwin
      - PATH=$HOME/Library/Python/2.7/bin:$PATH

    # Rust beta
    - rust: beta
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH

    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH

  allow_failures:
    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH

env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$HOME/.local/bin:$HOME/cached-deps/bin:$PATH
    - PACHYDERM_VERSION=1.9.8

before_install:
  - ./etc/travis_before_install.sh
before_script:
  - ./etc/travis_setup.sh
script:
  - ./etc/travis_test.sh

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  - chmod -R a+r $TRAVIS_BUILD_DIR/target
  - chmod -R a+r $HOME/cached-deps
cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $HOME/cached-deps
  # Increase default timeout of 3m
  timeout: 500

notifications:
  email:
on_success: never